sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
env:
  global:
    - BUILD_TIMEOUT=10000
install:
  - npm ci --ignore-scripts
before_install:
  - npm install --global npm@latest
script:
  - npm run ci